"""Common schemas and RFC 7807 problem details error models."""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ProblemDetails(BaseModel):
    """RFC 7807 compliant problem details error response model."""

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type.",
    )
    title: str = Field(..., description="A short, human-readable summary of the problem type.")
    status: int = Field(..., description="The HTTP status code generated by the origin server.")
    detail: str | None = Field(
        None, description="A human-readable explanation specific to this occurrence."
    )
    instance: str | None = Field(
        None, description="A URI reference that identifies the specific occurrence."
    )
    errors: list[dict[str, Any]] | None = Field(
        None, description="Detailed field-level validation errors if applicable."
    )

    model_config = ConfigDict(
        protected_namespaces=(),
        json_schema_extra={
            "example": {
                "type": "https://edgetwin.ai/errors/validation-error",
                "title": "Validation Error",
                "status": 422,
                "detail": "One or more request parameters failed validation.",
                "instance": "/api/v1/telemetry",
                "errors": [
                    {
                        "loc": ["body", "signals", "air_temp_c"],
                        "msg": "Input should be a valid number",
                    }
                ],
            }
        },
    )
